### ISSUE TITLE
Wrong resolution in moonlight-qt

### ISSUE THREAD

**Issue by pinembour** [veldenb/plugin.program.moonlight-qt#10]
Moonlight-qt seems to use the default resolution offered by the screen/TV, however for my TV it is not optimal at all and makes any text unreadable.

Is there a way to force moonlight-qt to display with a custom resolution ?

**Comment by veldenb** [comment]
Have you tried changing the resolution in the moonlight settings?
See https://user-images.githubusercontent.com/3607063/69664980-b5824980-1089-11ea-8094-568dfedc4625.jpg

**Comment by pinembour** [comment]
This setting does not change the resolution moonlight exposes to the TV, it only seems to change the resolution the distant PC renders at and sends over the network

**Comment by veldenb** [comment]
As far as I'm aware of moonlight-qt doesn't have an option to force the resolution. You could try the moonlight-qt discord channel or request the feature at https://github.com/moonlight-stream/moonlight-qt/issues
