### ISSUE TITLE
RPI 4 Libreelec Kodi

### ISSUE THREAD

**Issue by Marcel2508** [veldenb/plugin.program.moonlight-qt#14]
Hi,
I've installed and used the add-on successfully once already. But after I while when I tried it again it didn't work.
When I start the add-on I can only see a black screen. Noting more.

I tried reinstalling the add-on and docker but still the same. 
It's not even asking for configuration (after fresh install with previous uninstall including user data removal).
Kodi.log doesn't seem to log anything relevant..

Any Idea what could cause this behaviour?

**Comment by veldenb** [comment]
Does updating moonlight via the addon  configuration menu work?

**Comment by veldenb** [comment]
Feel free to try this new pre-release: https://github.com/veldenb/plugin.program.moonlight-qt/releases/tag/v0.1.4
If you problem still persist feel free to re-open the issue.
