### ISSUE TITLE
Is HEVC supported?

### ISSUE THREAD

**Issue by krisrok** [veldenb/plugin.program.moonlight-qt#15]
Just a quick question, is HEVC suppported as outlined [here](https://github.com/moonlight-stream/moonlight-docs/wiki/Installing-Moonlight-Qt-on-Raspberry-Pi-4#hevc-support)?

**Comment by veldenb** [comment]
Yes works. My personal experience is that HEVC works using 4K@60Hz till 15Mbps. On higher bit rates it looks like the Pi4 hardware decoder can't handle it using 4K. 
On lower resolutions higher bitrates do seem work.

**Comment by krisrok** [comment]
Thanks for your quick reply, sounds great. Maybe I just have to try and migrate to LE 10 again.

Oh and: Can you maybe think of anything regarding if this same approach should or shouldn‘t work on LibreELEC 9.x and [this plugin](https://github.com/clarkemw/script.moonlight-embedded-launcher)? I know it‘s a long shot but reading up on it there seem to be many factors at play ans you‘ll likely have deeper knowledge about them.

**Comment by veldenb** [comment]
When I started this project moonlight-qt was the only application that supported the pi4. I'm not sure moonlight-embedded has support for the pi4 now. This issue seems to indicate it does not: https://github.com/moonlight-stream/moonlight-embedded/issues/760

**Comment by cgutman** [comment]
Moonlight Embedded does support the Pi 4, but only via MMAL and the Fake KMS driver.

**Comment by veldenb** [comment]
Thanks for clarifying that :)
