### ISSUE TITLE
Support on Windows?

### ISSUE THREAD

**Issue by racerlucas** [veldenb/plugin.program.moonlight-qt#16]
Can you make it work on Windows?

**Comment by racerlucas** [comment]
Or at least make it work on Ubuntu or Debian cause libreelec not yet support the Xbox One wireless dongle

**Comment by veldenb** [comment]
@racerlucas could you try if this pre-release works for you on Ubuntu or Debian?
https://github.com/veldenb/plugin.program.moonlight-qt/releases/tag/v0.1.6
