### ISSUE TITLE
Starting Moonlight crash?

### ISSUE THREAD

**Issue by shoulih** [veldenb/plugin.program.moonlight-qt#20]
New installation of "LibreELEC-RPi4.arm-10.0.2.img" on Pi4 2MG and then Docker and  "plugin.program.moonlight-qt-0.1.6.zip" addon; Moonlight updated from the addon successfully.

When I launch Moonlight from Moonlight addon, it displays "Starting Moonlight..." and then goes back to Kodi

Did I miss anything?

**Comment by qbloomfield** [comment]
I'm having the same issue

**Comment by qbloomfield** [comment]
I tried running bootstrap_moonlight-qt.sh myself and the error I got was `mkdir: can't create directory '/moonlight-home': Read-only file system`

**Comment by qbloomfield** [comment]
Here is the output from that bootstrap script when ran from Kodi
```bash
Platform 'rpi' running 'libreelec' detected...
Loading profile...
Using Qt library from /storage/.kodi/userdata/addon_d
Running without window manager...
Detected resolution 4096,2160...
Using Qt scale factor 0.77...
Custom ALSA audio device: 'hdmi:CARD=vc4hdmi0,DEV=0'
Using Kodi hooks for libreelec...
--- Starting Moonlight ---
00:00:00 - Qt Info: Unable to detect Wayland or X11,
00:00:00 - Qt Info: Setting display mode by default.
00:00:00 - SDL Info (0): Compiled with SDL 2.23.0
00:00:00 - SDL Info (0): Running with SDL 2.23.0
00:00:00 - Qt Info: No translation available for  "C"
00:00:00 - Qt Warning: qrc:/gui/main.qml:12:1: QML Ap
00:00:00 - Qt Info: Found "gamecontrollerdb.txt" at "
00:00:00 - SDL Info (0): Loaded 208 new gamepad mappi
00:00:00 - SDL Info (0): V-sync disabled
00:00:00 - SDL Info (0): Sharing DRM FD with SDL
Segmentation fault

**Comment by veldenb** [comment]
There seems to be a change from moonlight-qt_4.1.0-1_arm64 to moonlight-qt_4.1.0-2_arm64 that causes this. I'll see if I can find something that is causing the issue.

**Comment by veldenb** [comment]
Does this version work for now? It should install the second last moonlight build: https://github.com/veldenb/plugin.program.moonlight-qt/releases/download/v0.1.6/plugin.program.moonlight-qt-0.1.6.zip

**Comment by qbloomfield** [comment]
That does work! Thank you! Do you know if there is a way to exit moonlight without a keyboard attached?

**Comment by veldenb** [comment]
It's a workaround for now and installs moonlight 4.1.0-1 instead of 4.1.0-2. You should be able to use your joypad to exit moonlight by pressing B several times and confirm with A when you see an confirmation dialog.

**Comment by shoulih** [comment]
I was able to launch Moonlight now

> Does this version work for now? It should install the second last moonlight build: https://github.com/veldenb/plugin.program.moonlight-qt/releases/download/v0.1.6/plugin.program.moonlight-qt-0.1.6.zip

I was able to launch Moonlight now, but I can't connect to the remote Game server from Azure Cloud with Nvidia Gamestream enabled for some reason.

**Comment by qbloomfield** [comment]
> It's a workaround for now and installs moonlight 4.1.0-1 instead of 4.1.0-2. You should be able to use your joypad to exit moonlight by pressing B several times and confirm with A when you see an confirmation dialog.

I'll have to see if my controller works in moonlight because it doesn't in libreelec. Says it is connected through Bluetooth but it won't detect any buttons when I try to configure it

**Comment by qbloomfield** [comment]
I'm only getting it to show my desktop wallpaper and my mouse when trying to stream steam, but on my PC it shows the steam big picture. Weird that it is still showing mouse movement but not the actual video being streamed. Would that be related to the downgraded version?

**Comment by veldenb** [comment]
Works fine on my own pi4, sounds more like an issue on the Windows side. Have you tried to disconnect your session (Start+Select+L1+R1 - Quit session) and then resume it from moonlight-qt?

**Comment by 03stevensmi** [comment]
Its Still Crashing! installed it for the very first time, moonight loads up fine, detects my pc fine, but as soon as i start a game, it just crashes, reloads up librelec and i cant seem to click on the kodi moonlight plugin unless i forcefully reboot my raspberry pi 4. any ideas?

**Comment by veldenb** [comment]
Did you try this version: https://github.com/veldenb/plugin.program.moonlight-qt/releases/tag/v0.1.6 ?

**Comment by 03stevensmi** [comment]
yep. if helps, im using analog output and not hdmi

**Comment by veldenb** [comment]
Hi @03stevensmi 

Sorry for the late response. Dit you try to also update moonlight itself from the plugin? The plugin version 0.1.6 should downgrade moonlight to 4.1.0-1. I also tried moonlight version 4.2.1 today but it has the same problem and crashes.

**Comment by cgutman** [comment]
Can you file an upstream bug for this?

**Comment by veldenb** [comment]
Hi @cgutman 

I created https://github.com/moonlight-stream/moonlight-qt/issues/868 with a new backtrace.
When creating the trace I noticed that moonlight 4.2.1 crashes at a later stage compared to 4.1.0-2. First it crashed on startup but now it starts but crashes on starting a stream. So looks like there is progress :)

**Comment by 03stevensmi** [comment]
> Hi @03stevensmi
> 
> Sorry for the late response. Dit you try to also update moonlight itself from the plugin? The plugin version 0.1.6 should downgrade moonlight to 4.1.0-1. I also tried moonlight version 4.2.1 today but it has the same problem and crashes.

I tried both 0.16 without updating through plugin, and 0.16 with updating the plugin. 
No matter what version (older, current and uptaded via plugin) I can't get anything. I gave up
at the end after backtracking older versions to see if a previous one works.
I haven't tried updating via plugin since we last spoke so if there is any progress and success,
Let me know @03stevensmi and I will try it out and test. I have subscribed to this project so I
Will see it ever on the day, or the next day latest.

But yeah, tried updating via plugin didn't work, trying various versions without updating also didn't work,
hell... Even had the exact same issue with retropie's official client with the exact same issue as kodi.
Games show up, but once a game is chosen, just black and crash. Nothing on the screen even flickers or changes. Just black, then home.

**Comment by veldenb** [comment]
@03stevensmi I released a new version, v0.1.7 contains a workaround for the crash when starting a stream.
It works on my pi4 now, can you confirm it works on your setup?

https://github.com/veldenb/plugin.program.moonlight-qt/releases/download/v0.1.7/plugin.program.moonlight-qt-0.1.7.zip

**Comment by 03stevensmi** [comment]
> @03stevensmi I released a new version, v0.1.7 contains a workaround for the crash when starting a stream. It works on my pi4 now, can you confirm it works on your setup?
> 
> https://github.com/veldenb/plugin.program.moonlight-qt/releases/download/v0.1.7/plugin.program.moonlight-qt-0.1.7.zip

hello, sorry for the late reply.
unfortunatly i am unable to test due to my whole house has been destroyed due to the pipe bursting and flooding the home. everything electrical wise was luckaly up stares so thats good, but i am unable to go back to my home until its safe.

and that could take a few weeks unfortunatly. 

also, i am  using my laptop to type this message and has f*ck all spell check.
really not going  to google every single word i typed so please ignor the shite spelling.

and one more thing i have to say is thank you so much for fixing this.
in am extreaml;y gratefull for the hard work you have done.

once thing (hopefully) get back to normal, this will be something i will look forward to testing out.
once again,
thank you.

**Comment by veldenb** [comment]
Wow that sounds terrible, hopefully everything gets fixed soon.
No rush, best of luck!

**Comment by 03stevensmi** [comment]
> Wow that sounds terrible, hopefully everything gets fixed soon. No rush, best of luck!

Thanks, at the moment things are going ... Ok. Looking at around 2 weeks when the floor gets sorted at the most before things get settled. The Good news is my grandad is an electrician and the electric is back on... Bad news is no water. Looking to hopefully be home some time next week at the least but when that happens I will be extremely busy sorting things back to normal. If its OK with everyone here until then, would it be ok If someone here reading this could possibly test this with a composite cable running at pal 720x576 libelec (no HDMI ofc) And report back if this works? Just so veldenb has an idea that all is good. This is basically what I have been trying to do with this plugin, so in theory if it works through composite pal, then it SHOULD most likely work with me. 

Once again, thanks for All your amazing work on this project.
Cheers,
03stevensmi

;)

**Comment by 03stevensmi** [comment]
Hey, just tried it out, it works great now! Thank you all for everything you have done! Keep up the good work.

**Comment by veldenb** [comment]
Great to hear and thanks for testing!
