### ISSUE TITLE
Add apps as separate home entries

### ISSUE THREAD

**Issue by Atemu** [veldenb/plugin.program.moonlight-qt#23]
I use this plugin to launch Steam BigPicture mode and nothing else. In order to do that I always need to go to Games -> Moonlight -> Steam BigPicture. Is it possible to add BPM to the Games screen directly?

**Comment by veldenb** [comment]
You can bookmark the entry in Kodi and access it via bookmarks.

**Comment by veldenb** [comment]
Closing stale issue for now
