### ISSUE TITLE
Request: Coreelec support

### ISSUE THREAD

**Issue by euro2** [veldenb/plugin.program.moonlight-qt#25]
I can install the addon, it says its installed succesfully, but doesnt run on coreelec. Did some toying around:

CoreELEC:~/.kodi/addons/plugin.program.moonlight-qt/resources/bin # bash get-platform.sh
Platform 'amlogic-ce' running 'coreelec' detected, using platform generic...

CoreELEC:~/.kodi/addons/plugin.program.moonlight-qt/resources/bin # bash launch_moonlight-qt.sh
Platform 'amlogic-ce' running 'coreelec' detected, using platform generic...
Running without window manager...
Detected resolution 1920,2160...
Using Qt scale factor 0.77...
--- Starting Moonlight ---
bootstrap_moonlight-qt.sh: line 207: ./moonlight-qt: cannot execute binary file: Exec format error

CoreELEC:~/.kodi/addons/plugin.program.moonlight-qt/resources/bin # bash bootstrap_moonlight-qt.sh
Platform 'amlogic-ce' running 'coreelec' detected, using platform generic...
Running without window manager...
Detected resolution 1920,2160...
Using Qt scale factor 0.77...
mkdir: can't create directory '/moonlight-home': Read-only file system
CoreELEC:~/.kodi/addons/plugin.program.moonlight-qt/resources/bin #

Dont know why its strike-through letters....

Is there a way to make this work?

**Comment by veldenb** [comment]
I think the plugin is trying to start the x86 binary, that will not work on amlogic. I'm not sure if there is a linux amlogic build for moonlight-qt.

**Comment by euro2** [comment]
ahhhhh got it thanks! Yes got Luna working, but no audio, so wanted to try this.

**Comment by JordanPlayz158** [comment]
How did you modify the`get-platform.sh` script to get it to grab the proper binary and such @euro2?
