### ISSUE TITLE
No access to settings with keyboard or mouse

### ISSUE THREAD

**Issue by harisma-git** [veldenb/plugin.program.moonlight-qt#26]
Hi there,

I installed the plugin and works wonderful. Thank you! The only issue i have is that i can not access the config menu of moonlight (the gear in the up-right corner) either with keyboard or mouse. I can only move with keyboard arrows between games and select them. Mouse not working at all. Both devices are connected via usb.

Rpi4 - Libreelec system

**Comment by veldenb** [comment]
Hi, the mouse is disabled because of a bug in moonlight-qt: https://github.com/moonlight-stream/moonlight-qt/issues/233
You should be able to navigate through the interface using the TAB-key and arrow keys.
Pressing Y on your game-pad should also show the config.
