### ISSUE TITLE
using wrong build path on wandboard (NXP Platform)

### ISSUE THREAD

**Issue by sm4rty-github** [veldenb/plugin.program.moonlight-qt#29]
When installing moonlight-qt it seems that the script is using the generic build path for x86 systems.

 sh ../bin/get-platform.sh
Platform 'nxp' running 'libreelec' detected, using platform generic...

But NXP (Wandboard Quad) is an arm device

then an error appears: cp stat not found
/usr/lib/x86_64-linux-gnu/libICE.so

trying to use the rpi build scripts by simply renaming the folders worked for compilation.

but when I try to start moonlight nothing happens. Kodi is killed successfully, then I have a black screen for a short time period and after that kodi relaunches.

when running launch-moonlight-qt.sh manually kodi is killed and this error appears on commandline

`Platform 'nxp' running 'libreelec' detected, using platform generic...
Loading LibreELEC profile for setting up environment...
Using custom libraries from /storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-qt/lib...
Using Qt library from /storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-qt/lib/qt5...
Running without window manager...
Detected resolution 1920,1080...
Using Qt scale factor 0.64...
Using Kodi hooks for libreelec...
--- Starting Moonlight ---
./moonlight-qt: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory`

uname -m returns "armv7l"

copying libssl.so from /usr/lib/ to moonlight-qt/lib/libssl.so.1.1 does the job for libssl

Now im stuck. copying libvchiq_arm.so from a raspberry results in this.
But after that I get:
`LibreWBQ:~/.kodi/addons/plugin.program.moonlight-qt/resources/bin # sh ./launch_moonlight-qt.sh
Platform 'nxp' running 'libreelec' detected, using platform armv7l...
Loading LibreELEC profile for setting up environment...
Using custom libraries from /storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-qt/lib...
Using Qt library from /storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-qt/lib/qt5...
Running without window manager...
Detected resolution 1920,1080...
Using Qt scale factor 0.64...
Using Kodi hooks for libreelec...
--- Starting Moonlight ---
./moonlight-qt: error while loading shared libraries: libvchiq_arm.so: cannot open shared object file: No such file or directory`

**Comment by veldenb** [comment]
Moonlight-qt currently does not release builds for the NXP platform. Raspberry pie 4 and generic x86 is supported.
