### ISSUE TITLE
Launcher Support for AKL

### ISSUE THREAD

**Issue by mousex110** [veldenb/plugin.program.moonlight-qt#32]
AKL has a gamestream plugin( works great), this scrapes all artwork and metadata from sunshine/gamestream. It will also launch moonlight on windows and android, but not librelec. Is there anyway that an akl launcher can be added for your build. Your addon does a great job of setting up moonlight-qt.
https://github.com/chrisism/script.akl.nvgamestream

**Comment by veldenb** [comment]
The project looks interesting, but would be beyond the scope of the current plugin.
Maybe I'll dive into it some day, for now I'm focusing on compatibility of the current plugin with LibreELEC 20.
