### ISSUE TITLE
ALSA pcm.c:8570:(snd_pcm_recover) underrun occurred

### ISSUE THREAD

**Issue by DeViLRuNNeR-dev** [veldenb/plugin.program.moonlight-qt#36]
I wanted to try using 5.1 audio streaming (Surround).
I cannot seem to get it working.
Stereo works great.

I am running LibreElec 11
`Linux LibreELEC11 6.1.19 #1 SMP Mon Mar 20 16:46:57 PDT 2023 x86_64 GNU/Linux`
On Regular x86 hardware with AMD Radeon R5-230 GPU (HDMI)

The log mentions ALSA underrun.
`00:00:22 - SDL Info (0): Starting audio stream...
00:00:22 - SDL Info (0): Desired audio buffer: 480 samples (5760 bytes)
00:00:22 - SDL Info (0): Obtained audio buffer: 480 samples (5760 bytes)
00:00:22 - SDL Info (0): Audio stream has 6 channels
00:00:22 - SDL Info (0): done
00:00:22 - SDL Info (0): Starting input stream...
00:00:22 - SDL Info (0): done
00:00:22 - SDL Info (0): Qt UI screen is at (0,0)
00:00:22 - SDL Info (0): SDL found matching display 0
ALSA lib /mnt/datadev/LibreELEC/LibreELEC.tv/build.LibreELEC-Generic-legacy.x86_64-11.0.1-DualAudio-r12/build/alsa-lib-1.2.8/src/pcm/pcm.c:8570:(snd_pcm_recover) underrun occurred
ALSA lib /mnt/datadev/LibreELEC/LibreELEC.tv/build.LibreELEC-Generic-legacy.x86_64-11.0.1-DualAudio-r12/build/alsa-lib-1.2.8/src/pcm/pcm.c:8570:(snd_pcm_recover) underrun occurred
ALSA lib /mnt/datadev/LibreELEC/LibreELEC.tv/build.LibreELEC-Generic-legacy.x86_64-11.0.1-DualAudio-r12/build/alsa-lib-1.2.8/src/pcm/pcm.c:8570:(snd_pcm_recover) underrun occurred
00:00:23 - SDL Info (0): Found display mode with desktop resolution: 1920x1080x60
`

**Comment by veldenb** [comment]
Moonlight-qt seems to start as it should, so I think this is an upstream issue (https://github.com/moonlight-stream/moonlight-qt/issues/1041).
