### ISSUE TITLE
`generic_git` Dockerfile can't be built

### ISSUE THREAD

**Issue by ArtemkaKun** [veldenb/plugin.program.moonlight-qt#38]
# Steps to reproduce:

1. Copy on local PC https://github.com/veldenb/plugin.program.moonlight-qt/blob/main/resources/build/generic_git/Dockerfile
2. `docker build .`

# Expected

Successful build

# Got

```
E: Unable to locate package libfreetype-dev
The command '/bin/sh -c /bin/bash -c /opt/scripts/install-base-deps.sh &&     apt-get install -y --no-install-recommends libwayland-dev wayland-protocols libva-dev libvdpau-dev &&     apt-get clean -y &&     rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
```

# Additional info

[This](https://github.com/cgutman/moonlight-packaging/blob/master/scripts/install-base-deps.sh) dependencies installer script seems to cause an error after the #72ec840 commit

```
if [ "$DISTRO" != "buster" ] && [ "$DISTRO" != "bionic" ]; then
    apt-get install -y libfreetype-dev
else
    apt-get install -y libfreetype6-dev
fi
```

# Possible solution

`DISTRO` variable must be set up to `buster`, since `generic_git` Dockerfile based on `debian:buster` image

```
ENV DISTRO=buster
```

**Comment by cgutman** [comment]
Oh I didn’t know anyone was using those scripts outside of my Dockerfiles.

FWIW, I plan to publish generic V4L2 stateful+stateless armhf and aarch64 Debian packages for the next release in addition to the existing Raspbian-specific armhf/aarch64 packages. Hopefully that can reduce the amount of duplicated work between here and upstream.

**Comment by ArtemkaKun** [comment]
Not sure if I got you right, but I'm not using this Dockerfile separately from moonlight plugin. I decided to investigate the issue that prevents me from installing moonlight on my LibreELEC 11.0.3 x86 miniPC

**Comment by veldenb** [comment]
The `generic_git` is meant for debugging and trying moonlight-qt releases not yet released.
Manually running `cd resources/build/ && sh build.sh` should be the way to go if you want to debug the install process.
For your system it should build using `resources/build/generic/Dockerfile`

**Comment by ArtemkaKun** [comment]
Ah yes, you are right. I see an error for install dependencies command on my LibreELEC when installing this addon in "normal" way, something like "... returned with the code 1".

Will try to build it manually and will see if I will find anything

**Comment by veldenb** [comment]
Continues in https://github.com/veldenb/plugin.program.moonlight-qt/issues/39
