### ISSUE TITLE
0.3.1 does not work on my device

### ISSUE THREAD

**Issue by ClassicDarkChocolate** [veldenb/plugin.program.moonlight-qt#40]
How can I resolve this issue? I've tried LibreELEC 11 Generic, LibreELEC 11 Legacy Generic, and LibreELEC 10, but none of them worked.

Here's my log 

LibreELEC 10 Generic + plugin.program.moonlight-qt 0.3.1

```
Platform 'generic' running 'libreelec' detected...
Loading LibreELEC profile for setting up environment...
Using custom libraries from /storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-qt/lib...
Using Qt library from /storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-qt/lib/qt5...
Running with window manager...
Using Kodi hooks for libreelec...
--- Starting Moonlight ---
00:00:00 - Qt Info: Could not load the Qt platform plugin "xcb" in "/storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-qt/lib/qt5/plugins/" even though it was found.
00:00:00 - Qt Fatal: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

Aborted
```

LibreELEC 11 Legacy Generic + plugin.program.moonlight-qt 0.3.1

```
Platform 'generic' running 'libreelec' detected...
Loading LibreELEC profile for setting up environment...
Using custom libraries from /storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-qt/lib...
Using Qt library from /storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-qt/lib/qt5...
Running with window manager...
Using Kodi hooks for libreelec...
--- Starting Moonlight ---
00:00:00 - SDL Info (0): Compiled with SDL 2.25.0
00:00:00 - SDL Info (0): Running with SDL 2.25.0
00:00:00 - Qt Info: No translation available for "C"
00:00:00 - Qt Info: No existing credentials found
00:00:00 - Qt Info: Wrote new identity credentials to settings
00:00:00 - Qt Warning: qrc:/gui/main.qml:12:1: QML ApplicationWindow: ToolTip must be attached to an Item
00:00:01 - Qt Info: Found "gamecontrollerdb.txt" at ":/data/gamecontrollerdb.txt"
00:00:01 - SDL Info (0): Loaded 225 new gamepad mappings
00:00:01 - SDL Info (0): V-sync disabled
libva info: VA-API version 1.17.0
libva info: Trying to open /usr/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_17
libva error: /usr/lib/dri/iHD_drv_video.so init failed
libva info: va_openDriver() returns 1
00:00:01 - SDL Info (0): Trying fallback VAAPI driver names
libva info: VA-API version 1.17.0
libva info: User environment variable requested driver 'iHD'
libva info: Trying to open /usr/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_17
free(): double free detected in tcache 2
Aborted
```

**Comment by ClassicDarkChocolate** [comment]
Only this combination works without problems: LibreELEC 10 Generic + plugin.program.moonlight-qt 0.2.1

**Comment by veldenb** [comment]
I don't own a system with a Intel iGPU so I can't test your setup. Does LibreELEC 11 (non-Legacy) Generic + plugin.program.moonlight-qt 0.3.1 work? There are some hardware support differences between the LibreELEC Legacy and non-Legacy installation.

**Comment by ClassicDarkChocolate** [comment]
> I don't own a system with a Intel iGPU so I can't test your setup. Does LibreELEC 11 (non-Legacy) Generic + plugin.program.moonlight-qt 0.3.1 work? There are some hardware support differences between the LibreELEC Legacy and non-Legacy installation.

Unfortunately, only LibreELEC 10 Generic + plugin.program.moonlight-qt 0.2.1 works.

**Comment by veldenb** [comment]
I tried the plugin on a Intel NUC today and had no problems.
- LibreELEC 11 Generic + plugin.program.moonlight-qt 0.3.1: Works only with software rendering enabled in moonlight
- LibreELEC 11 Legacy Generic + plugin.program.moonlight-qt 0.3.1: Works with hardware accelerated HEVC

Log of LibreELEC 11 Legacy Generic + plugin.program.moonlight-qt 0.3.1:
```
Platform 'generic' running 'libreelec' detected...
Loading LibreELEC profile for setting up environment...
Using custom libraries from /storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-qt/lib...
Using Qt library from /storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-qt/lib/qt5...
Running with window manager...
Using Kodi hooks for libreelec...
--- Starting Moonlight ---
00:00:00 - SDL Info (0): Compiled with SDL 2.25.0
00:00:00 - SDL Info (0): Running with SDL 2.25.0
00:00:00 - Qt Info: No translation available for "C"
00:00:00 - Qt Warning: qrc:/gui/main.qml:12:1: QML ApplicationWindow: ToolTip must be attached to an Item
00:00:00 - Qt Debug: "Not supported"
00:00:00 - Qt Info: Found "gamecontrollerdb.txt" at "/storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-home/.cache/Moonlight Game Streaming Project
/Moonlight/gamecontrollerdb.txt"
00:00:00 - SDL Info (0): Loaded 295 new gamepad mappings
00:00:01 - SDL Info (0): V-sync disabled
libva info: VA-API version 1.17.0
libva info: Trying to open /usr/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_17
libva info: va_openDriver() returns 0
00:00:01 - SDL Info (0): Initialized VAAPI 1.17
00:00:01 - SDL Info (0): Driver: Intel iHD driver for Intel(R) Gen Graphics - 22.6.6 (9a33cd2)
00:00:01 - FFmpeg: [AVHWDeviceContext @ 0x7f6c140cb0c0] Format 0x41524742 -> bgra.
00:00:01 - FFmpeg: [AVHWDeviceContext @ 0x7f6c140cb0c0] Format 0x42475241 -> argb.
00:00:01 - FFmpeg: [AVHWDeviceContext @ 0x7f6c140cb0c0] Format 0x41424752 -> rgba.
00:00:01 - FFmpeg: [AVHWDeviceContext @ 0x7f6c140cb0c0] Format 0x52474241 -> abgr.
00:00:01 - FFmpeg: [AVHWDeviceContext @ 0x7f6c140cb0c0] Format 0x58524742 -> bgr0.
00:00:01 - FFmpeg: [AVHWDeviceContext @ 0x7f6c140cb0c0] Format 0x42475258 -> 0rgb.
...
```

What are your hardware specs?

**Comment by ClassicDarkChocolate** [comment]
It's [VivoMini UN42](https://www.asus.com/commercial-desktop/vivomini_un42_commercial/specifications/)

**Comment by veldenb** [comment]
@cgutman could it be that Intel Celeron (2957U) from 2013 is not well supported under moonlight?

**Comment by ClassicDarkChocolate** [comment]
> @cgutman could it be that Intel Celeron (2957U) from 2013 is not well supported under moonlight?

Should I move this issue to Moonlight-qt? Also, could you explain the difference between versions 0.2.1 and 0.3.1?

**Comment by cgutman** [comment]
I really can't say without knowing where that crash is happening. Can you run it under gdb and get a stack trace?

**Comment by veldenb** [comment]
> @ClassicDarkChocolate: Should I move this issue to Moonlight-qt? Also, could you explain the difference between versions 0.2.1 and 0.3.1?

I don't think that's necessary, I noticed some missing libraries that seem to be needed on LibreELEC 10 but not on 11 for some reason. Maybe some other code path is triggered on 10. I added them so we can check if this fixes your issues om LibreELEC 10 and maybe on 11.

Could you try [plugin.program.moonlight-qt-main.zip](https://github.com/veldenb/plugin.program.moonlight-qt/files/12838091/plugin.program.moonlight-qt-main.zip) first on LibreELEC 10 and then on LibreELEC 11 to check if this works better?

**Comment by ClassicDarkChocolate** [comment]
> > @ClassicDarkChocolate: Should I move this issue to Moonlight-qt? Also, could you explain the difference between versions 0.2.1 and 0.3.1?
> 
> I don't think that's necessary, I noticed some missing libraries that seem to be needed on LibreELEC 10 but not on 11 for some reason. Maybe some other code path is triggered on 10. I added them so we can check if this fixes your issues om LibreELEC 10 and maybe on 11.
> 
> Could you try [plugin.program.moonlight-qt-main.zip](https://github.com/veldenb/plugin.program.moonlight-qt/files/12838091/plugin.program.moonlight-qt-main.zip) first on LibreELEC 10 and then on LibreELEC 11 to check if this works better?

I just tried installing it on 10 and it works, thanks. I will try it on 11 later.

**Comment by ClassicDarkChocolate** [comment]
No luck on getting it work on 11 Legacy Generic

```
Platform 'generic' running 'libreelec' detected...
Loading LibreELEC profile for setting up environment...
Using custom libraries from /storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-qt/lib...
Using Qt library from /storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-qt/lib/qt5...
Running with window manager...
Using Kodi hooks for libreelec...
--- Starting Moonlight ---
00:00:00 - SDL Info (0): Compiled with SDL 2.25.0
00:00:00 - SDL Info (0): Running with SDL 2.25.0
00:00:00 - Qt Info: No translation available for "C"
00:00:00 - Qt Info: No existing credentials found
00:00:00 - Qt Info: Wrote new identity credentials to settings
00:00:00 - Qt Warning: qrc:/gui/main.qml:12:1: QML ApplicationWindow: ToolTip must be attached to an Item
00:00:01 - Qt Info: Found "gamecontrollerdb.txt" at ":/data/gamecontrollerdb.txt"
00:00:01 - SDL Info (0): Loaded 225 new gamepad mappings
00:00:01 - SDL Info (0): V-sync disabled
libva info: VA-API version 1.17.0
libva info: Trying to open /usr/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_17
libva error: /usr/lib/dri/iHD_drv_video.so init failed
libva info: va_openDriver() returns 1
00:00:01 - SDL Info (0): Trying fallback VAAPI driver names
libva info: VA-API version 1.17.0
libva info: User environment variable requested driver 'iHD'
libva info: Trying to open /usr/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_17
free(): double free detected in tcache 2
Aborted
```

**Comment by veldenb** [comment]
Are you familiair with gdb to get a stack trace?

**Comment by ClassicDarkChocolate** [comment]
> Are you familiair with gdb to get a stack trace?

I have no experience with it, can you give me some hints on how to?

**Comment by ClassicDarkChocolate** [comment]
It's strange. Today, I tried to install Moonlight from a fresh LibreELEC 10 and [plugin.program.moonlight-qt-main.zip](https://github.com/veldenb/plugin.program.moonlight-qt/files/12838091/plugin.program.moonlight-qt-main.zip), but it didn't work.

```
Platform 'generic' running 'libreelec' detected...
Loading LibreELEC profile for setting up environment...
Using custom libraries from /storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-qt/lib...
Using Qt library from /storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-qt/lib/qt5...
Running with window manager...
Using Kodi hooks for libreelec...
--- Starting Moonlight ---
./moonlight-qt: symbol lookup error: /tmp/.mount_moonlitdsGmQ/usr/bin/../lib/libQt5QuickTemplates2.so.5: undefined symbol: _ZTI20QAccessibleQuickItem, version Qt_5_PRIVATE_API
```

**Comment by veldenb** [comment]
Looks like an incompatibility between the plugin and the newly released moonlight-qt 5.0.0. 
I probably need to add some other libraries to the build.

**Comment by veldenb** [comment]
For moonlight-qt 5 I needed to create separate builds for LibreELEC 10 and 11. LibreELEC 10 only works with libraries from Debian Bullseye and LibreELEC 11 only with libraries from Debian bookworm. After updating the plugin and moonlight-qt it seems to be running well on a Intel 6th gen i3. Can you give this one ([plugin.program.moonlight-qt-main.zip](https://github.com/veldenb/plugin.program.moonlight-qt/files/13196861/plugin.program.moonlight-qt-main.zip))
 a spin to see if it works?

**Comment by ClassicDarkChocolate** [comment]
> For moonlight-qt 5 I needed to create separate builds for LibreELEC 10 and 11. LibreELEC 10 only works with libraries from Debian Bullseye and LibreELEC 11 only with libraries from Debian bookworm. After updating the plugin and moonlight-qt it seems to be running well on a Intel 6th gen i3. Can you give this one ([plugin.program.moonlight-qt-0.4.0.zip](https://github.com/veldenb/plugin.program.moonlight-qt/files/13209421/plugin.program.moonlight-qt-0.4.0.zip)) a spin to see if it works?
> 
> edit: updated build to latest release

I just tried it. It works pretty well on both 10 and 11. Thank you!

Moonlight doesn't show up in the games menu in the Arctic: Zephyr - Reloaded theme, though. It worked before. I don't know if this is an issue with the theme.

**Comment by ClassicDarkChocolate** [comment]
Is it possible to launch plugin with `RunPlugin()`?

**Comment by veldenb** [comment]
Running `RunPlugin(plugin://plugin.program.moonlight-qt)` should start it.

**Comment by ClassicDarkChocolate** [comment]
> Running `RunPlugin(plugin://plugin.program.moonlight-qt)` should start it.

It ain't work.

**Comment by veldenb** [comment]
If it shows up in the default Estuary theme then I think it's an issue with the custom Zephyr theme.
As an alternative you could try to create a bookmark to the plugin.
