### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by superk0ch** [veldenb/plugin.program.moonlight-qt#46]
Hello.

Today I tried to update Moonlight-QT to the current version under LibreElec 11.0.3, but I always get an abort with an error message. A new installation did not help either. Docker is up to date and running.
![20231120_130136](https://github.com/veldenb/plugin.program.moonlight-qt/assets/151539427/1d8f8e91-795f-47d6-b858-5ed9c1a535c1)
![20231120_130151](https://github.com/veldenb/plugin.program.moonlight-qt/assets/151539427/5a7568cb-e875-49da-8021-e30ad0aa2311)
![20231120_130203](https://github.com/veldenb/plugin.program.moonlight-qt/assets/151539427/9aefc174-7954-4d39-8c54-561a4d94e50d)
![20231120_130211](https://github.com/veldenb/plugin.program.moonlight-qt/assets/151539427/3f45e336-bd8b-4e52-9b89-be1c3056012a)

**Comment by veldenb** [comment]
Can you send your `/storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/build.log` file?

**Comment by superk0ch** [comment]
[build.log](https://github.com/veldenb/plugin.program.moonlight-qt/files/13430023/build.log)

**Comment by veldenb** [comment]
Could it be the case that you ran out of disk space or Docker got corrupted somehow?
You could try the command's in this comment and try again: https://github.com/veldenb/plugin.program.moonlight-qt/issues/39#issuecomment-1751740820.

Another method could be a full clean install of LibreELEC if that's an option for you.

**Comment by superk0ch** [comment]
ok, thank you. will try it today.

**Comment by superk0ch** [comment]
sorry that i came up with such a simple problem. you where exactly right, i was running out of disk space. the commands from the comment was helping me. thank you so much and keep up the good work.
