### ISSUE TITLE
Intel N100 (alder lake) hardware support

### ISSUE THREAD

**Issue by lodesmets** [veldenb/plugin.program.moonlight-qt#47]
I got the message that no supported GPU could be found, and moonlight would fall back to software decoding.

But I'm using an Intel N100 mini pc. It has integrated graphics.

The OS I'm using is libreelec. I tried different versions (both nightly and regular). But now I'm using the nightly version with Linux kernel v 6.6.0.

Moonlight QT version I'm using it V5.0.1

Is here the correct place to report it? Or should I report it with libreelec?

**Comment by veldenb** [comment]
Have you tried the LibreELEC Legacy image?
See also https://github.com/veldenb/plugin.program.moonlight-qt#hardware-acceleration-on-libreelec-11-generic-x86_64-doesnt-work

**Comment by kayti** [comment]
I have similar problem with UHD 600. But using legacy image of libreelec isn't really an answer, because in legacy I can't play movies in HDR mode :P Any advice?

**Comment by veldenb** [comment]
Not really, hardware acceleration without X or wayland isn't very well supported yet. See also https://github.com/veldenb/plugin.program.moonlight-qt/issues/44#issuecomment-1796130115 and the upstream bug report.

So if the legacy image works for streaming and the normal image doesn't, the legacy image is the best we can do right now.

**Comment by lodesmets** [comment]
> Have you tried the LibreELEC Legacy image? See also https://github.com/veldenb/plugin.program.moonlight-qt#hardware-acceleration-on-libreelec-11-generic-x86_64-doesnt-work

Yep, this is the solution. I used the GBM version. Because it said for newer pc's. But apparently i had to use  Legacy (i didn't use it because it said it is for older pc's and the N100 is very new.
