### ISSUE TITLE
LibreELEC 12 silently failing to launch moonlight-qt

### ISSUE THREAD

**Issue by witchent** [veldenb/plugin.program.moonlight-qt#49]
Hey there,

It seems like an update of LibreELEC 12 broke this addon for some reason I cannot completely figure out.

Using the latest LibreELEC 12 nightly, the addon silently fails while trying to source ``/etc/profile``. I tracked it down a bit and the failure occurs while sourcing ``/etc/profile.d/99-kodi.conf``.
Then I looked for changes to this file in recent time and found this commit:
https://github.com/LibreELEC/LibreELEC.tv/commit/065d3f5e88e6444b3514c9c14ab41089c9d4ba49

And indeed, if I manually revert that commit everything works as intended. Using shell I can however source ``/etc/profile``, so I sadly do not know why it fails using the addon.

Maybe you have a better idea about this stuff?

**Comment by veldenb** [comment]
Need to check that on my pi4, maybe the new version errors out for some reason.
Anything useful in moonlight-qt.log?

**Comment by witchent** [comment]
Sadly nothing, not even with debug mode on. It just stops after trying to source kodi.conf

**Comment by timhae** [comment]
it will be fixed once https://github.com/LibreELEC/LibreELEC.tv/pull/8471 is merged

**Comment by veldenb** [comment]
Thanks for the info

**Comment by veldenb** [comment]
@witchent the above merge request is merged, does the latest nightly fix your issue?

**Comment by timhae** [comment]
It did for me

**Comment by veldenb** [comment]
I'll be closing the issue then.

**Comment by witchent** [comment]
Sorry, didn't have time to test thsi before, but indeed it seems to have fixed the problem.
