### ISSUE TITLE
Moonlight Add-on fails to run (solved) / Vertical tile - LE 10 nightly RPi4 4GB 

### ISSUE THREAD

**Issue by elbolutony** [veldenb/plugin.program.moonlight-qt#5]
Hi, i'm trying in nightly 'cause the 4K60P support, fresh after a reboot, just ran once. 

This is an extract:

2021-07-09 19:46:22.759 T:1145    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'apps'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.program.moonlight-qt/addon.py", line 226, in <module>
                                                       show_gui(addon_handle, page_mode, page_host_id, page_game_id)
                                                     File "/storage/.kodi/addons/plugin.program.moonlight-qt/addon.py", line 157, in show_gui
                                                       show_games(handle, hosts, host_id)
                                                     File "/storage/.kodi/addons/plugin.program.moonlight-qt/addon.py", line 134, in show_games
                                                       for app_id, app in host['apps'].items():
                                                   KeyError: 'apps'
                                                   -->End of Python script error report<--

If i find a solution, i'll mark it solved/close the issue. 

[kodi.log](https://github.com/veldenb/plugin.program.moonlight-qt/files/6794211/kodi.log)

**Comment by elbolutony** [comment]
Well, i deleted the moonlight.conf file in /storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-home/.config/Moonlight Game Streaming Project and ran.
Now, looks like the rendering (HEVC/H.265) is wrong, vertically it shows OK, but horizontally i only see 2 icons of the taskbar (with all the above icons and desk) and then it repeats the same 14 times, for a total of 15 colums.
i'll keep tinkering!

**Comment by veldenb** [comment]
> Hi, i'm trying in nightly 'cause the 4K60P support, fresh after a reboot, just ran once.
> 
> This is an extract:
> 
> 2021-07-09 19:46:22.759 T:1145 ERROR : EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
> - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
> Error Type: <class 'KeyError'>
> Error Contents: 'apps'
> Traceback (most recent call last):
> File "/storage/.kodi/addons/plugin.program.moonlight-qt/addon.py", line 226, in
> show_gui(addon_handle, page_mode, page_host_id, page_game_id)
> File "/storage/.kodi/addons/plugin.program.moonlight-qt/addon.py", line 157, in show_gui
> show_games(handle, hosts, host_id)
> File "/storage/.kodi/addons/plugin.program.moonlight-qt/addon.py", line 134, in show_games
> for app_id, app in host['apps'].items():
> KeyError: 'apps'
> -->End of Python script error report<--
> 
> If i find a solution, i'll mark it solved/close the issue.
> 
> [kodi.log](https://github.com/veldenb/plugin.program.moonlight-qt/files/6794211/kodi.log)

Hi, thanks for reporting. If fixed the Python error in this commit: https://github.com/veldenb/plugin.program.moonlight-qt/commit/20c790fc1fdddb7d04a6ccb491a29807dda3f5aa
It will be in the next release but you can download the main branch if you need the fix sooner.

I don't think I can help you with the HVEC problem, sounds more like a Moonlight-qt issue so I'll close this issue. Feel free to open a new one if you encounter errors :)

**Comment by piercy** [comment]
I too am getting this vertical tiling problem after installing.  Has anyone managed to solve it?

**Comment by elbolutony** [comment]
Hi piercy, not yet, i was somewhat assisting SupervisedThinking (ST) to get that working, but i couldn't manage to mix that with the code here yet and maybe it's completly unrelated. 

For a little more info check: 
https://forum.libreelec.tv/thread/23644-libreelec-rr-10-x-brave-spotify-moonlight-emulationstation-retroarch-pegasus/?postID=152623#post152623

As of this writing, ST and this fork of LibreELEC went quiet. 
If i've got any news i'll post it.

**Comment by elbolutony** [comment]
Hi @piercy i recommend you to follow this in issue #9
