### ISSUE TITLE
Addon update failed on RPI5 with error: No such file or directory

### ISSUE THREAD

**Issue by danielgallik** [veldenb/plugin.program.moonlight-qt#50]
I have clean install of LibreELEC (11.0.4) on RPi5. 
Then I installed docker and moonlight, but on first moonlight start it fails with error:
![screenshot00000](https://github.com/veldenb/plugin.program.moonlight-qt/assets/6614417/db45aad8-81df-4bf2-abc9-96f3c178d0bf)

I checked path from error in logs: "Updating moonlight-qt finished with 776 lines of output and exit-code 0: cp: cannot stat '/usr/lib/aarch64-linux-gnu/libGL.so*': No such file or directory"
Directory "aarch64-linux-gnu" not exists.
I am not sure if it is problem because of RPi5, or I am missing some dependency.

**Comment by veldenb** [comment]
Rpi 5 support is still somewhat experimental and I don't own one for testing. I added the libgl dependency, can you try if [this version](https://github.com/veldenb/plugin.program.moonlight-qt/archive/refs/heads/main.zip) works better?

**Comment by danielgallik** [comment]
I reinstalled addon, but still the same issue. I will try to manually install the lib.

**Comment by veldenb** [comment]
Can you send your `build.log`? You should be able to find it here: `/storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/build.log`

**Comment by danielgallik** [comment]
[build.log](https://github.com/veldenb/plugin.program.moonlight-qt/files/13779849/build.log)

**Comment by veldenb** [comment]
Looks like Docker tries to use 32-bit arm instead of 64-bit. Can you try [the latest version](https://github.com/veldenb/plugin.program.moonlight-qt/archive/refs/heads/main.zip)? It includes a change to enforce 64-bit.

**Comment by danielgallik** [comment]
This one finally fixed the installation process, great job and I have a new problem. Moonlight is updated now, but when I start it than whole system crashes and restarts itself.

**Comment by veldenb** [comment]
Hard to tell, anything in your `moonlight-qt.log`?
You'll find it here: `/storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-qt.log`.

**Comment by danielgallik** [comment]
nothing usefull, also I did not found anything abount this crash in kodi logs
[moonlight-qt.log](https://github.com/veldenb/plugin.program.moonlight-qt/files/13855189/moonlight-qt.log)
[01_KODI.log](https://github.com/veldenb/plugin.program.moonlight-qt/files/13855190/01_KODI.log)
[01_KODI_CRASH.log](https://github.com/veldenb/plugin.program.moonlight-qt/files/13855191/01_KODI_CRASH.log)

**Comment by veldenb** [comment]
Might be a driver related issue, have you tried the LibreELEC 12 nightly builds?
Others seem to have more progress there, apart from issue https://github.com/veldenb/plugin.program.moonlight-qt/issues/49. But that should be fixed in the upcoming nightly.

**Comment by veldenb** [comment]
I'm closing this because the remaining issue seems driver/hardware related and not the the plugin itself. It looks like LibreELEC 12 works better with the Pi5: https://github.com/veldenb/plugin.program.moonlight-qt/issues/49
