### ISSUE TITLE
Can't close the stream

### ISSUE THREAD

**Issue by shnaps** [veldenb/plugin.program.moonlight-qt#54]
I'm using the latest provided plugin for moonlight (0.4.3) with libreelec 11.0.5 on Pi4. Host is Windows PC with sunshine 0.21.0 to stream stuff. I have BT keyboard+mouse combo connected to my Pi4 device.
My issue is that when I stream the full desktop, there is no option to close the stream anymore. Ctrl+Alt+Shift+Q doesn't work and none of the other moonlight shortcuts work as well. At the same time all windows shortcuts like Alt+Tab, Ctrl+Shift+ESC, etc work just fine. I tried to check if this could be connected to the option for moonlight to capture system shortcuts and send them to the host but this option is enabled and greyed out by default and I can't change it.

**Comment by veldenb** [comment]
Hi, this sounds more like a moonlight-qt issue. The only thing this plugin does is starting moonlight-qt, so if moonlight-qt itself does not work well it's better to open an issue on the moonlight-qt issue tracker: https://github.com/moonlight-stream/moonlight-qt/issues

**Comment by shnaps** [comment]
Could it be related to grayed out capture system shortcuts option? If not I guess I'll create an issue on moonlight-qt tracker.

**Comment by veldenb** [comment]
Maybe, but this plugin has no influence on that setting. That's also part of moonlight.

**Comment by shnaps** [comment]
Gotcha. I'll report it to the right place then.
