### ISSUE TITLE
Failing to install

### ISSUE THREAD

**Issue by zjkree** [veldenb/plugin.program.moonlight-qt#56]
When I try to open Moonlight addon after installing from zip file, I get an error: `Update failed: sudo: a password is required.`

I am running Kodi on NixOS on a RBP4. The kodi session is ran by a user in the wheel group.

**Comment by zjkree** [comment]
Closing this since I realized this is meant for LibreELEC, not any Kodi setup.

**Comment by veldenb** [comment]
NixOS is indeed not supported.
