### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by Jorys-Paulin** [veldenb/plugin.program.moonlight-qt#6]
Hello, I would like to contribute a translation for French (France) to this plugin. I have already translated the strings, but it seems like there's also Crowdin metadata, and I want to make sure it is correct before creating a pull request.
```diff
# Kodi Media Center language file
# Addon Name: Moonlight
# Addon id: plugin.program.moonlight-qt
# Addon Provider: veldenb
msgid ""
msgstr ""
"Report-Msgid-Bugs-To: veldenb\n"
-"Language: en_GB\n"
+"Language: fr_FR\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"X-Crowdin-Project: pluginprogrammoonlight-qt\n"
"X-Crowdin-Project-ID: 457400\n"
-"X-Crowdin-Language: en-GB\n"
+"X-Crowdin-Language: fr\n"
"X-Crowdin-File: strings.po\n"
"X-Crowdin-File-ID: 2\n"
"Project-Id-Version: pluginprogrammoonlight-qt\n"
"Content-Type: text/plain; charset=UTF-8\n"
-"Language-Team: English, United Kingdom\n"
-"PO-Revision-Date: 2021-05-24 14:48\n"
+"Language-Team: French\n"
+"PO-Revision-Date: 2021-07-12 14:00\n"
```

**Comment by veldenb** [comment]
Hi, the metadata looks ok. I will import it into Crowdin for the final check but the most important part are the translated strings :)

**Comment by Jorys-Paulin** [comment]
Thanks for the feedback! I've opened pull request #7 with my changes, they are ready to be merged.

**Comment by veldenb** [comment]
Thanks for the translation, can you check if it works well in the latest release?
https://github.com/veldenb/plugin.program.moonlight-qt/releases/download/v0.1.2/plugin.program.moonlight-qt.zip

**Comment by Jorys-Paulin** [comment]
I've already checked that everything looks good by patching the current release. Everything is displayed correctly, even with strings 1.5x longer than English!

**Comment by veldenb** [comment]
Thanks! I will close the issue then, I added your name to the change log :)
Au Revoir!
