### ISSUE TITLE
Resolution of the laptop screen on moonlight instead of the second screen

### ISSUE THREAD

**Issue by moi952** [veldenb/plugin.program.moonlight-qt#62]
Hello,

Os: LibreELEC Generic Legacy 11.0.6.
I use LibreELEC on a laptop with a usb-c to HDMI adapter, in the LibreELEC settings I set the output to dp2 with the resolution of my TV.

But when I launch moonlight the image is blurry, I have the impression that it recovers the resolution of the "default" screen instead of taking the resolution selected for dp2.

Is it possible to help me?

Thanks,
Charly

**Comment by veldenb** [comment]
Can you send your logfile when starting moonlight-qt on dp2?
It's located in `/storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-qt.log`.

**Comment by moi952** [comment]
Thanks for your quick answer :) 
I found a solution, if I active "blank other display" in display setting, moonlight launch in 4k, but scale is not verry good, display is very small ^^
<img width="1161" alt="Capture d’écran 2024-03-13 à 20 03 17" src="https://github.com/veldenb/plugin.program.moonlight-qt/assets/52632400/1a4e8d41-6b44-4283-a6d9-5c516567c240">

I give you log
[moonlight-qt.log](https://github.com/veldenb/plugin.program.moonlight-qt/files/14592848/moonlight-qt.log)

I wanted to know if I have the possibility of integrating a moonlight-qt that I developed?
If yes how can I do this? 

Thanks for your work !

**Comment by veldenb** [comment]
The output and resolution settings work only on EGL systems like the Raspberry pi. Your system is running X with a window manager. You can change the resolution in moonlight-qt itself, but that only works for the stream. Not the moonlight-qt menu.

> I wanted to know if I have the possibility of integrating a moonlight-qt that I developed?

I only support versions from the official repository, but feel free to fork.

**Comment by moi952** [comment]
> The output and resolution settings work only on EGL systems like the Raspberry pi. Your system is running X with a window manager. You can change the resolution in moonlight-qt itself, but that only works for the stream. Not the moonlight-qt menu.
> 
> > I wanted to know if I have the possibility of integrating a moonlight-qt that I developed?
> 
> I only support versions from the official repository, but feel free to fork.

The resolution of my system is 4k on libreElec, but the scaling is not done. On Windows and on Fedora in 4k the covers are bigger.
If it's impossible it's not a big deal but it would be extra comfort :p

Thank you for your answer
