### ISSUE TITLE
Small fix for more compatibility with skins (add "executable" to <provides>)

### ISSUE THREAD

**Issue by AllesMeins** [veldenb/plugin.program.moonlight-qt#63]
I've been having a lot of problems getting this plugin to run in other skins than the default one. Mainly because most skins (even those in the official repo) don't come with support for "Game addons". With them you have to go through addons -> my addons -> game providers -> moonlight or similar to launch the addon - with some skins like "copacetic" starting moonlight isn't even possible at all. 

Also the "skin shortcuts"-lib that many skins use doesn't support linking to game addons. Bottom line: I didn't find one alternative skin where you could comfortably use moonlight. 

Luckily after some digging I found a surprisingly easy fix: Could you just change "**&lt;provides&gt;game&lt;/provides&gt;**" to **&lt;provides&gt;game executable&lt;/provides&gt;** in the addon.xml? This adds moonlight as a standalone addon to "Program Addons". Of cause I don't get the list of installed games in alternative skins but at least I can start moonlight (and add shortcuts to it) and take it from there.

Disclaimer: I've no idea about addon development - so if you know about any nasty side effects of changing it, than don't. I did some testing on my two systems and couldn't find any :-)

**Comment by veldenb** [comment]
Seems an easy fix, can you try [this version](https://github.com/veldenb/plugin.program.moonlight-qt/archive/refs/heads/main.zip)? It has the executable option.

**Comment by AllesMeins** [comment]
Thanks, works great for me!

**Comment by moi952** [comment]
> Seems an easy fix, can you try [this version](https://github.com/veldenb/plugin.program.moonlight-qt/archive/refs/heads/main.zip)? It has the executable option.

It's perfect, I can integrate all Moonlight games as a console game (with widget in Copacetic theme or Embuary theme)

<img width="1513" alt="Capture d’écran 2024-03-15 à 22 24 45" src="https://github.com/veldenb/plugin.program.moonlight-qt/assets/52632400/fd1fae5c-2a21-4ba1-808e-1d5fba55f6e9">

Do you know if it's complicated to add sorts/filters? Like “Recently Played” for example

Thanks you !

**Comment by moi952** [comment]
> Seems an easy fix, can you try [this version](https://github.com/veldenb/plugin.program.moonlight-qt/archive/refs/heads/main.zip)? It has the executable option.

Sorry to bother you with this, but it seems to me that it is possible to display a background image, I saw that in principle there is one, do you know why it is not displayed ( it has the same behavior for all themes)

I tell myself that an implementation that fetches the game's fanart to look like a console could be great <3

And could you tell me if it is possible to choose the “games” to display in the extension settings? Because I have games that aren't really games I would like them to be hidden

Thank you very much for your work

PS: the modification you made will you make it available to everyone?

**Comment by AllesMeins** [comment]
> <img alt="Capture d’écran 2024-03-15 à 22 24 45" width="1513" src="https://private-user-images.githubusercontent.com/52632400/313338786-fd1fae5c-2a21-4ba1-808e-1d5fba55f6e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NTQ3MzQsIm5iZiI6MTcxMDc1NDQzNCwicGF0aCI6Ii81MjYzMjQwMC8zMTMzMzg3ODYtZmQxZmFlNWMtMmEyMS00YmExLTgwOGUtMWQ1ZmJhNTVmNmU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDA5MzM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1ZDRkMWRlYzA1ZmNlMWEzY2E0Mzk5NmZjODg3ZDk5NWUxNDE3MzE0ODQxMzc3ZTg4YWUxMDBhZDQ1MDAxNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0i4Ugb-uuQ3fFlvwfjZ2UMeUHY7i7B2t0jGYIAw03eY">

I hope you don't mind if I ask you a question, @moi952 that's only loosely related to the add-on. I see you have a lot of games there. Did you add them all manually into your moonlight/sunshine or do you have some sort of tool that imports your library automatically. If yes: what do you use?

**Comment by moi952** [comment]
> > <img alt="Capture d&apos;écran 2024-03-15 à 22 24 45" width="1513" src="https://private-user-images.githubusercontent.com/52632400/313338786-fd1fae5c-2a21-4ba1-808e-1d5fba55f6e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NTQ3MzQsIm5iZiI6MTcxMDc1NDQzNCwicGF0aCI6Ii81MjYzMjQwMC8zMTMzMzg3ODYtZmQxZmFlNWMtMmEyMS00YmExLTgwOGUtMWQ1ZmJhNTVmNmU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDA5MzM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1ZDRkMWRlYzA1ZmNlMWEzY2E0Mzk5NmZjODg3ZDk5NWUxNDE3MzE0ODQxMzc3ZTg4YWUxMDBhZDQ1MDAxNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0i4Ugb-uuQ3fFlvwfjZ2UMeUHY7i7B2t0jGYIAw03eY">
> 
> J'espère que cela ne vous dérange pas si je vous pose une question,@moi952ce n'est que vaguement lié au module complémentaire. Je vois que tu as beaucoup de jeux là-bas. Les avez-vous tous ajoutés manuellement dans votre clair de lune/soleil ou disposez-vous d'une sorte d'outil qui importe automatiquement votre bibliothèque. Si oui : qu'utilisez-vous ?

I use https://github.com/Nonary/PlayNiteWatcher
It work with playnite, you can configure games covers format (quare for me) and you can get official description game, title etc ... 

And after you use playNiteWatcher for extrat all your games :)

**Comment by veldenb** [comment]
> Do you know if it's complicated to add sorts/filters? Like “Recently Played” for example

The information for the filters is not available from moonlight-qt, so we would need to track the usage in the plugin itself, I think it would be possible to make. You could create a new issue for that (this one seems to be solved).

> Sorry to bother you with this, but it seems to me that it is possible to display a background image, I saw that in principle there is one, do you know why it is not displayed ( it has the same behavior for all themes)

I'm not sure, it might be possible but may also depend on the used view. You could create a new issue for that.

> I tell myself that an implementation that fetches the game's fanart to look like a console could be great <3

I have no experience with that and I suspect it would require quite some work. Currently cached artwork from Moonlight-qt is used.

> And could you tell me if it is possible to choose the “games” to display in the extension settings? Because I have games that aren't really games I would like them to be hidden

Hiding games would be harder than sorting the latest used games. I would prefer the sorting because it's less work to implement.
