### ISSUE TITLE
No Hardware Acceleration using Libreelec generic 11.95

### ISSUE THREAD

**Issue by Erfboom** [veldenb/plugin.program.moonlight-qt#68]
I've read some things here and there about hardware support but I'm still not clear on a few things.

The Readme says if hardware support doesn't work it's because of gbm and legacy x11 will work. However, x11 doesn't support hdr so I'm out of luck right? I saw a few other forum posts saying there's missing libraries or ffmpeg missing or some later builds of moonlight work, but this is using Docker so it should have everything built in unless I'm missing something.

Any insight?

**Comment by veldenb** [comment]
I'm not sure what your question is, do you want to know how well HDR is supported?

**Comment by Erfboom** [comment]
Yes. :).

**Comment by veldenb** [comment]
To my knowledge that's currently not possibly on the Generic x86 image.
I know it does work for both scenario's on the Raspberry Pi 4 and presumably 5.
