### ISSUE TITLE
Impossible to install on LibreElec 12 Generic

### ISSUE THREAD

**Issue by moi952** [veldenb/plugin.program.moonlight-qt#69]
Hi,

I have just installed LibreElec 12 Generic but the installation of the plugin is impossible I get the message "Docker is not installed, please install the kodi Docker add-on"

So I installed it manually, Docker is activated but I still get this message.

I use the version here https://github.com/veldenb/plugin.program.moonlight-qt/issues/63#issuecomment-1998052791

My PC is an HP laptop with an AMD 5400u APU

Thank you for your help :)

**Comment by veldenb** [comment]
Did you reboot after installing Docker?

**Comment by moi952** [comment]
> Did you reboot after installing Docker?

Thanks <3 
After reboot it's working :)
