### ISSUE TITLE
Batocera : missing libMangoHud.so.

### ISSUE THREAD

**Issue by Griffures** [veldenb/plugin.program.moonlight-qt#74]
Host : RPI4 / RAM; 4GB / GPU : V3D 4.2
OS : Batocera 39
Windowing system ; Wayland
Running Kodi Media Center 20.2

Trying to install plugin.program.moonlight-qt-0.4.4.zip, then launching it for the first time :

`Update failed: ERROR: ld.so: object 'libMangoHud.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored`
Then installation aborts.

Batocera uses pacman, but with different repositories so I can't install lib32-mangohud from the extra/multilib repository, unless I try touch up my pacman.conf or build it from source.

Also fun fact : batocera runs as root, so sudo ain't there.

Is that OS too singular for the install script to support it ?

**Comment by veldenb** [comment]
From what I'm aware of moonlight has no dependencies for MangoHud. I assume it's something in your local configuration that causes the issue.
