### ISSUE TITLE
Crash when opening Moonlight

### ISSUE THREAD

**Issue by demon2749** [veldenb/plugin.program.moonlight-qt#77]
I've set up a old chromebook (Acer C710-2833) to serve as a streaming device. I installed LibreELEC generic-legacy 12.0.1, docker 12.0.0.6, and enabled ssh to install the plugin.

I got as far as updating Moonlight, where after it then fails to start. Loading bar reaches about 50%, freezes, and then it will crash Kodi.

I dont see anything in the log, but it appears to be reset after each crash.
https://paste.kodi.tv/ubarowemac

Ive tried:
1.  Using both generic and generic-legacy libreelec 12.0.1
2.  Changing the egl card to 0 and 1.

I'm very unfamiliar with Kodi, i was just looking for a lightweight moonlight client and this seemed like a good way to do it.

Not sure what steps to take next.

**Comment by veldenb** [comment]
Hi, can you post your `/storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-qt.log` ?

**Comment by demon2749** [comment]
> Hi, can you post your `/storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-qt.log` ?

https://pastebin.com/gasQ0ctd

**Comment by GearCzech** [comment]
Hello, I've had similiar problem and forcing an older version of moonlight-qt worked #79

**Comment by veldenb** [comment]
Should be fixed in v0.4.5.
