### ISSUE TITLE
Moonlight crashing in the middle of loading

### ISSUE THREAD

**Issue by GearCzech** [veldenb/plugin.program.moonlight-qt#78]
The app restarts the system when it hits 50%.

Tried:
- reverting to libreelec 11
- using legacy version
- downgrading the docker
- downgrading the plugin

nothing worked though

my log output:
LibreELEC:~/.kodi/userdata/addon_data/plugin.program.moonlight-qt # cat moonlight-qt.log
Platform 'generic' running 'libreelec' detected...
Loading LibreELEC profile for setting up environment...
Using custom libraries from /storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-qt/lib...
Using Qt library from /storage/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-qt/lib/qt5...
Forcing mode 1920x1080...
Running with window manager...
Using Kodi hooks for libreelec...
--- Starting Moonlight ---
./moonlight-qt: symbol lookup error: /tmp/.mount_moonliFaodbD/usr/bin/../lib/libQt5QuickTemplates2.so.5: undefined symbol: _ZTI20QAccessibleQuickItem, version Qt_5_PRIVATE_API

**Comment by veldenb** [comment]
Should for now be fixed in v0.4.5. Thanks for the PR :)
