### ISSUE TITLE
(Question) Use Pulseaudio audio card? // Solved with workaround. 

### ISSUE THREAD

**Issue by elbolutony** [veldenb/plugin.program.moonlight-qt#8]
Hi, there's a way to use a PA card? Mi main audio card is plugged into a router with OpenWRT and routed through PulseAudio.  
My autostart.sh in LibreELEC makes it the default audio card in Kodi. 
But this plugin/add-on uses ALSA. 

Thanks!

**Comment by elbolutony** [comment]
Update: i've solved it modifiying the bootstrap_moonlight-qt.sh script but any update will undo this workaround, so i'll leave this Issue open. 
Thanks again! 

[bootstrap_moonlight-qt.zip](https://github.com/veldenb/plugin.program.moonlight-qt/files/6878203/bootstrap_moonlight-qt.zip)

**Comment by veldenb** [comment]
Maybe, I will have to figure out a way to detect if the audio device is using pulseaudio or not. Another option could be an extra configuration item.

**Comment by elbolutony** [comment]
IMHO an option is acceptable, defaulting to ALSA and PA as an option for being a non-standard setup.

**Comment by veldenb** [comment]
Can you check if this version works for you? It should detect PulseAudio automatically and configure the audio device you configured in Kodi. It should now essentially do the same for pulse as it does for ALSA.

[plugin.program.moonlight-qt.zip](https://github.com/veldenb/plugin.program.moonlight-qt/files/6881629/plugin.program.moonlight-qt.zip)

**Comment by elbolutony** [comment]
Hi veldenb, just tested, it works, awesome. 
Closing this issue, thanks.
